### ISSUE TITLE
Doesn't output correct results

### ISSUE THREAD

**Issue by Nazchanel** [theninthsky/godaddy-scraper#6]
I cross checked `results.csv` and the godaddy website and it is showing taken when the domain is not taken. May have something to do with the API.

**Comment by theninthsky** [comment]
@Nazchanel
Thank you for the information!
Unfortunately, I can no longer maintain this project, so I won't be able to fix this.

Thanks again and sorry about it.

**Comment by Nazchanel** [comment]
👍
